[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/chilia2
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 2
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Chilia2
inputFile = /home/val/code/cesmc_ru/etico/dataset/CHILIA2_100m_reg.nc
windowSize = 9
startLat = 45.334
startLon = 29.766
initialDirection = NW
maxIterations = 1000
initPhase = 10
depthTolerance = 0.2
endLat = 45.34
endLon = 29.653
endDistance = 250
maxComebacks = 20

[Validation]
transects = [[[45.343, 29.654], [45.337, 29.654]],[[45.347, 29.664], [45.342, 29.664]],[[45.35, 29.68], [45.344, 29.68]],[[45.35, 29.693], [45.346, 29.693]],[[45.353, 29.704], [45.348, 29.704]],[[45.349, 29.719], [45.334, 29.719]],[[45.347, 29.724], [45.340, 29.724]],[[45.344, 29.747], [45.338, 29.747]],[[45.342, 29.755], [45.337, 29.755]],[[45.342, 29.761], [45.335, 29.761]]]