[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/chilia3
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 2
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Chilia 3
inputFile = /home/val/code/cesmc_ru/etico/dataset/CHILIA3_100m_reg.nc
windowSize = 9
startLat = 45.22
startLon = 29.741
initialDirection = NW
maxIterations = 1000
initPhase = 10
depthTolerance = 0.2
endLat = 45.339
endLon = 29.652
endDistance = 250
maxComebacks = 20

[Validation]
transects = [[[45.335, 29.648], [45.335, 29.66]],[[45.321, 29.657], [45.321, 29.667]],[[45.306, 29.666], [45.306, 29.675]],[[45.287, 29.668], [45.287, 29.678]],[[45.27, 29.672], [45.27, 29.684]],[[45.254, 29.683], [45.254, 29.692]],[[45.245, 29.697], [45.249, 29.705]],[[45.236, 29.708], [45.24, 29.72]],[[45.227, 29.718], [45.227, 29.734]],[[45.223, 29.726], [45.223, 29.75]]]