[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/chilia1
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 1
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Chilia1
inputFile = /home/val/code/cesmc_ru/etico/dataset/CHILIA1_100m_reg.nc
windowSize = 9
startLat = 45.463
startLon = 29.781
initialDirection = SW
maxIterations = 1000
initPhase = 10
depthTolerance = 0.2
endLat = 45.389
endLon = 29.594
endDistance = 250
maxComebacks = 20

[Validation]
transects = [[[45.394, 29.601], [45.388, 29.601]],[[45.41, 29.62], [45.405, 29.624]],[[45.426, 29.643], [45.42, 29.645]],[[45.435, 29.661], [45.428, 29.663]],[[45.438, 29.673], [45.431, 29.673]],[[45.44, 29.694], [45.434, 29.694]],[[45.45, 29.718], [45.44, 29.718]],[[45.456, 29.747], [45.451, 29.748]],[[45.454, 29.739], [45.45, 29.742]],[[45.463, 29.773], [45.456, 29.775]]]