[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/dritta
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png

[Plot]
dotSize = 0.3
plotDots = True
dotsInterval = 2
dotsFontSize = 1
dotsFontColour = black
plotStartPoint = True
plotEndPoint = True
plotColour = red
startPointSize = 2
startPointMarker = x
startPointColour = black
endPointSize = 2
endPointMarker = x
endPointColour = black

[Input]
inputFile = /home/val/code/cesmc_ru/etico/dataset/DRITTA_10m_reg.nc
windowSize = 9
startLat = 44.9698
startLon = 12.5492
initialDirection = W
maxIterations = 500
initPhase = 10
depthTolerance = 0.2
endLat = 44.9536
endLon = 12.303
endDistance = 250
