[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/gnocca
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png

[Plot]
dotSize = 1
plotDots = True
dotsInterval = 10
dotsFontSize = 1
dotsFontColour = black
plotStartPoint = True
plotEndPoint = True
plotColour = red
startPointSize = 2
startPointMarker = x
startPointColour = black
endPointSize = 2
endPointMarker = x
endPointColour = black

[Input]
inputFile = /home/val/code/cesmc_ru/etico/dataset/GNOCCA_10m_reg.nc
windowSize = 9
startLat = 44.8098
startLon = 12.4194
initialDirection = W
maxIterations = 700
initPhase = 10
depthTolerance = 0.2
endLat = 44.9522
endLon = 12.3014
endDistance = 250
