[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/gnocca
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 1
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = darkorange
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Po Gnocca
inputFile = /home/val/code/cesmc_ru/etico/dataset/GNOCCA_10m_reg.nc
windowSize = 9
startLat = 44.8098
startLon = 12.4194
initialDirection = W
maxIterations = 700
initPhase = 10
depthTolerance = 0.2
endLat = 44.9522
endLon = 12.3014
endDistance = 250
maxComebacks = 20

[Validation]
transects = [[[44.9466, 12.2998], [44.9466, 12.3034]],[[44.9374, 12.3032], [44.9408, 12.3062]],[[44.93, 12.3226], [44.9296, 12.3276]],[[44.9106, 12.3148], [44.9098, 12.3176]],[[44.8928, 12.3254], [44.8922, 12.3292]],[[44.873, 12.342], [44.876, 12.3442]],[[44.8626, 12.3606], [44.8634, 12.3642]],[[44.8422, 12.371], [44.8428, 12.376]],[[44.8226, 12.3818], [44.8246, 12.3862]],[[44.8092, 12.4144], [44.8144, 12.415]]]