[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/gorofull
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 1
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Po Goro
inputFile = /home/val/code/cesmc_ru/etico/dataset/GORO_10m_FULL_reg.nc
windowSize = 9
startLat = 44.9733
startLon = 12.0525
# startLat = 44.9278
# startLon = 12.233
initialDirection = SE
maxIterations = 2000
initPhase = 10
depthTolerance = 0.2
# endLat = 44.7907
# endLon = 12.3999
endLat = 44.7909
endLon = 12.3991
# endLat = 44.9278
# endLon = 12.233
endDistance = 250
maxComebacks = 20

[Validation]
transects = [[[44.967, 12.0575], [44.9733, 12.0575]],[[44.9622, 12.098], [44.9637, 12.1028]],[[44.9412, 12.1226], [44.943, 12.1268]],[[44.9391, 12.17], [44.946, 12.17]],[[44.9226, 12.2126], [44.9319, 12.2126]],[[44.9379, 12.2801], [44.9421, 12.2873]],[[44.9046, 12.2807], [44.9046, 12.2879]],[[44.8512, 12.3113], [44.8607, 12.3158]],[[44.8293, 12.3431], [44.8296, 12.3497]],[[44.8023, 12.3731], [44.8059, 12.3779]]]