[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/gorofull
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 1
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = darkorange
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Po Goro
inputFile = /home/val/code/cesmc_ru/etico/dataset/GORO_10m_FULL_reg.nc
windowSize = 9
startLat = 44.9733
startLon = 12.0525
# startLat = 44.9278
# startLon = 12.233
initialDirection = SE
maxIterations = 2000
initPhase = 10
depthTolerance = 0.2
# endLat = 44.7907
# endLon = 12.3999
endLat = 44.7909
endLon = 12.3991
# endLat = 44.9278
# endLon = 12.233
endDistance = 250
maxComebacks = 20