[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/maistra
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png

[Plot]
dotSize = 1
plotDots = True
dotsInterval = 2
dotsFontSize = 1
dotsFontColour = black
plotStartPoint = True
plotEndPoint = True
plotColour = red
startPointSize = 2
startPointMarker = x
startPointColour = black
endPointSize = 2
endPointMarker = x
endPointColour = black

[Input]
inputFile = /home/val/code/cesmc_ru/etico/dataset/MAISTRA_10m_reg.nc
windowSize = 9
startLat = 45.0363
startLon = 12.4104
initialDirection = SW
maxIterations = 70
initPhase = 10
depthTolerance = 0.3
endLat = 44.9563
endLon = 12.3265
endDistance = 250
