[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/maistra
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 5
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Po Maistra
inputFile = /home/val/code/cesmc_ru/etico/dataset/MAISTRA_10m_reg.nc
windowSize = 9
startLat = 45.0363
startLon = 12.4104
initialDirection = SW
maxIterations = 600
initPhase = 10
depthTolerance = 0.3
endLat = 44.9563
endLon = 12.3265
endDistance = 100
maxComebacks = 20