[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/maistra
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 5
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Po Maistra
inputFile = /home/val/code/cesmc_ru/etico/dataset/MAISTRA_10m_reg.nc
windowSize = 9
startLat = 45.0363
startLon = 12.4104
initialDirection = SW
maxIterations = 600
initPhase = 10
depthTolerance = 0.3
endLat = 44.9563
endLon = 12.3265
endDistance = 100
maxComebacks = 20

[Validation]
transects = [[[45.0325, 12.4091], [45.0327, 12.4117]],[[45.0163, 12.4109], [45.0169, 12.4134]] ,[[45.0049, 12.418], [45.0018, 12.418]],[[44.9993, 12.3962], [44.9972, 12.3973]],[[44.99, 12.3854], [44.9886, 12.3873]],[[44.9921, 12.369], [44.9898, 12.3674]],[[44.9987, 12.3608], [44.9963, 12.3605]],[[44.9948, 12.3435], [44.9925, 12.345]],[[44.9807, 12.3406], [44.9803, 12.3435]],[[44.9647, 12.3344], [44.9638, 12.3364]]]