[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
StartDir = NW
StartLat = 44.8092
StartLon = 12.4192
EndLat = 44.9597
EndLon = 12.423

[Plot]
PointSparsity = 5
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.79
LatMax = 44.96
LonMin = 12.29
LonMax = 12.44
PlotSteps = False

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output_GNOCCA.log
ThalwegFile = thalweg_GNOCCA.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 1250
ThalwegStop = 1300