[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
StartDir = W
StartLat = 44.9698
StartLon = 12.5498
EndLat = 44.928
EndLon = 12.233

[Plot]
PointSparsity = 5
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.94
LatMax = 44.99
LonMin = 12.28
LonMax = 12.58
PlotSteps = False

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output_GORO.log
ThalwegFile = thalweg_GORO.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 720
ThalwegStop = 720