[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
StartDir = SW
StartLat = 45.0363
StartLon = 12.4104
EndLat = 44.9535
EndLon = 12.3201
MaxSteps = 1000
StopDistance = 0.5
DistanceWeight = 2.0
DepthWeight = 1.0
DirectionWeight = 1.0
HistoryDirectionWeight = 1.5

[Plot]
PointSparsity = 5
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.9536
LatMax = 45.0394
LonMin = 12.321
LonMax = 12.4286
PlotSteps = False
CBarMin = 0
CBarMax = 50
ColorMap = viridis

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/thalweg/2025/ETICO/output/maistra
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/thalweg/2025/ETICO/output/maistra
BaselinePlotName = baseline.png
LogFile = output_MAISTRA.log
ThalwegFile = thalweg_MAISTRA.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 720
ThalwegStop = 720