[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
Radius = 1
StartDir = W
StartLat = 44.969
StartLon = 12.543
EndLat = 44.976
EndLon = 12.053
MaxSteps = 1000
StopDistance = 0.5
DistanceWeight = 2.0
DepthWeight = 1.0
DirectionWeight = 1.0
HistoryDirectionWeight = 1.5
OptimisationSteps = 3
BacktrackSteps = 5

[Plot]
PointSparsity = 5
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.94
LatMax = 44.99
LonMin = 12
LonMax = 12.7
PlotSteps = False
CBarMin = 0
CBarMax = 15
ColorMap = GnBu
CloseUp = True

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/thalweg/2025/ETICO/output/dritta
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/thalweg/2025/ETICO/output/dritta
BaselinePlotName = baseline.png
LogFile = output_DRITTA.log
ThalwegFile = thalweg_DRITTA.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 720
ThalwegStop = 720