[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
StartLat = 44.933
StartLon = 12.159
EndLat = 44.928
EndLon = 12.233

[Plot]
PointSparsity = 1
PointsEnabled = True
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.925
LatMax = 44.947
LonMin = 12.14
LonMax = 12.18
PlotSteps = False

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output.log

[Debug]
PlotStartPoint = 0
PlotEndPoint = 200
ThalwegStop = 200