[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
StartDir = SE
StartLat = 44.973
StartLon = 12.0522
EndLat = 44.928
EndLon = 12.233
MaxSteps = 1000
StopDistance = 0.5
DistanceWeight = 2.0
DepthWeight = 1.0
DirectionWeight = 1.0
HistoryDirectionWeight = 1.5

[Plot]
PointSparsity = 5
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.77
LatMax = 45
LonMin = 12.03
LonMax = 12.43
PlotSteps = False
CBarMin = 0
CBarMax = 50
ColorMap = viridis

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/thalweg/2025/ETICO/output/goro
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/thalweg/2025/ETICO/output/goro
BaselinePlotName = baseline.png
LogFile = output_GORO_full.log
ThalwegFile = thalweg_GORO_full.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 2820
ThalwegStop = 2820