[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
StartLat = 44.8709
StartLon = 12.4807
EndLat = 44.9509
EndLon = 12.431

[Plot]
PointSparsity = 5
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.865
LatMax = 44.953
LonMin = 12.42
LonMax = 12.49
PlotSteps = False

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output_TOLLE.log
ThalwegFile = thalweg_TOLLE.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 670
ThalwegStop = 670