[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9

[Plot]
PointSparsity = 25
PointsEnabled = true
PointsSize = 0.5
LabelsEnabled = false
LabelsSize = 0.4

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png