[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 5
StartDir = SE
StartLat = 45.392
StartLon = 29.595
EndLat =   45.464
EndLon =   29.782

[Plot]
PointSparsity = 1
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 45.38 
LonMin = 29.58
LatMax = 45.48
LonMax = 29.8
PlotSteps = False

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output_CHILIA1.log
ThalwegFile = thalweg_CHILIA1.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 178
ThalwegStop = 178