[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9
StartDir = NW
StartLat = 44.8709
StartLon = 12.4807
EndLat = 44.9509
EndLon = 12.431
MaxSteps = 500
StopDistance = 0.5
DistanceWeight = 2.0
DepthWeight = 1.0
DirectionWeight = 1.0
HistoryDirectionWeight = 1.5

[Plot]
PointSparsity = 5
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 44.865
LatMax = 44.953
LonMin = 12.42
LonMax = 12.49
PlotSteps = False
CBarMin = 0
CBarMax = 50
ColorMap = viridis

[Output]
OutputDirectory = ~/code/cesmc_ru/estuarIO/thalweg/EstuarIO_thalweg/output
PlotDirectory = ~/code/cesmc_ru/estuarIO/thalweg/EstuarIO_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output_TOLLE.log
ThalwegFile = thalweg_TOLLE.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 670
ThalwegStop = 670