[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 5
StartDir = NW
StartLat = 45.334
StartLon = 29.767
EndLat = 45.335
EndLon = 29.652

[Plot]
PointSparsity = 1
PointsEnabled = False
PointsSize = 0.35
LabelsEnabled = False
LabelsSize = 2
LatMin = 45.31
LatMax = 45.36
LonMin = 29.64
LonMax = 29.77
PlotSteps = False

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output_CHILIA2.log
ThalwegFile = thalweg_CHILIA2.csv

[Debug]
PlotStartPoint = 0
PlotEndPoint = 88
ThalwegStop = 88
