[Algorithm]
MaxSearchAlgo = Classic
WindowSize = 9

[Plot]
PointSparsity = 1
PointsEnabled = true
PointsSize = 0.35
LabelsEnabled = true
LabelsSize = 2
LatMin = 44.925
LatMax = 44.947
LonMin = 12.14
LonMax = 12.18
PlotSteps = True

[Output]
OutputDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/output
PlotDirectory = /home/val/code/cesmc_ru/estuarIO/swi/estuario_thalweg/plots
BaselinePlotName = baseline.png
LogFile = output.log

[Debug]
PlotStartPoint = 130
PlotEndPoint = 145
ThalwegStop = 250