[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/sulina
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 0
plotDots = False
dotsInterval = 2
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = magenta
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = magenta
endPointSize = 2
endPointMarker = x
endPointColor = magenta

[Input]
name = Po Dritta
inputFile = /home/val/code/cesmc_ru/etico/dataset/SULINA_100m_reg.nc
windowSize = 9
startLat = 45.147
startLon = 29.766
initialDirection = NW
maxIterations = 1000
initPhase = 10
depthTolerance = 0.2
endLat = 45.187
endLon = 28.892
endDistance = 250
maxComebacks = 20