[Output]
baseFolder = /home/val/code/cesmc_ru/etico/output/tolle
thalwegCsvFile = thalweg.csv
thalwegPngFile = thalweg.png
simplifiedCsvFile = greedy.csv
simplifiedPngFile = greedy.png
simplifiedNcFile = greedy.nc

[Plot]
riverColorMap = GnBu
dotSize = 1
plotDots = True
dotsInterval = 3
dotsFontSize = 1
dotsFontColor = black
plotStartPoint = True
plotEndPoint = True
plotColor = red
optiPlotColor = navy
startPointSize = 2
startPointMarker = x
startPointColor = black
endPointSize = 2
endPointMarker = x
endPointColor = black

[Input]
name = Po Tolle
inputFile = /home/val/code/cesmc_ru/etico/dataset/TOLLE_10m_reg.nc
windowSize = 9
startLat = 44.8703
startLon = 12.4818
initialDirection = NW
maxIterations = 500
initPhase = 10
depthTolerance = 0.2
endLat = 44.9492
endLon = 12.4335
endDistance = 250
maxComebacks = 20

[Validation]
transects = [[[44.8717, 12.4757], [44.8755, 12.4793]], [[44.8937, 12.4616], [44.8933, 12.4667]], [[44.907, 12.4543], [44.9117, 12.455]], [[44.9027, 12.4647], [44.9039, 12.4678]], [[44.907, 12.4575], [44.9091, 12.4584]], [[44.9084, 12.4477], [44.9117, 12.4501]], [[44.9117, 12.4404], [44.9149, 12.4434]], [[44.9187, 12.4329], [44.9187, 12.4367]], [[44.9302, 12.4305], [44.9302, 12.4355]], [[44.9358, 12.4327], [44.9358, 12.4373]], [[44.948, 12.4291], [44.9477, 12.4369]]]